---


- name: Download Filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elasticsearch.version }}-amd64.deb
    dest: ~/filebeat-{{ elasticsearch.version }}-amd64.deb


- name: Install Filebeat
  apt:
     deb: ~/filebeat-{{ elasticsearch.version }}-amd64.deb

- name: Config filebeat
  template: src=filebeat.yml dest=/etc/filebeat/filebeat.yml



- name: Restart elasticseacrh
  shell: sudo systemctl restart filebeat.service
  ignore_errors: yes





