---

- name: Ensure PostgreSQL Python libraries are installed
  apt: name="{{ postgresql_python_library }}" state=present update_cache=true

- name: install postrgres
  apt:
   name="{{ item }}"
   state=absent 
   update_cache=true
  with_items:
   - postgresql-contrib
   - postgresql 

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: change postgres network binding
  lineinfile:
    path: /etc/postgresql/9.5/main/pg_hba.conf
    regexp: '# listen_addresses'
    line: "listen_addresses = '*'"  

- name: change postgres network binding
  lineinfile:
    path: /etc/postgresql/9.5/main/pg_hba.conf
    regexp: 'host  all  all 0.0.0.0/0 md5'
    line: 'host  all  all 0.0.0.0/0 md5'

- name: create postgresql db
  postgresql_db:
    name: "your-db-name"
    state: present
  become: true
  become_user: postgres