---

- name: Add epel-release repo
  yum:
     name: epel-release
     state: present

- name: install nginx
  yum: name=nginx state=present update_cache=true

- name: restart nginx
  shell: systemctl restart nginx



