---

- name: Creates directory kafka
  file:
    path: /opt/kafka
    state: directory

- name: Download kafka
  get_url:
    url: https://www.apache.org/dist/kafka/2.1.1/kafka_2.11-2.1.1.tgz
    dest: /opt/kafka/kafka.tgz

- name: Extract kafka
  unarchive:
    src: /opt/kafka/kafka.tgz
    dest: /opt/kafka
   

- name: move direktori
  shell: mv /opt/kafka/kafka_2.11-2.1.1/* /opt/kafka/
  ignore_errors: yes



- name: Config config kafka
  template: src=server.properties dest=/opt/kafka/config/server.properties

- name: Config config zookeeper
  template: src=zookeeper.properties dest=/opt/kafka/config/zookeeper.properties

- name: Config service kafka
  template: src=kafka.service dest=/etc/systemd/system/kafka.service

- name: Config service zookeeper
  template: src=zookeeper.service dest=/etc/systemd/system/zookeeper.service


- name: enable zookeeper dan kafka
  shell: systemctl enable zookeeper;systemctl start zookeeper;systemctl enable kafka ;systemctl start kafka
  ignore_errors: yes