---

- name: Install aptitude
  become: true
  apt:
    name: aptitude

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes


- name: Install utilities
  become: true
  apt:
    name: "{{ item }}"
  with_items: "{{ vm.tools }}"

- name: Install Java 8 JRE
  become: true
  apt:
    name: openjdk-8-jre-headless


- name: Download Jmeter
  get_url:
    url: http://apache.belnet.be/jmeter/binaries/apache-jmeter-{{ jmeter.version }}.tgz
    dest: /opt/apache-jmeter-{{ jmeter.version }}.tgz

- name: move folder jmeter
  shell: cd /opt/ && tar -xzvf apache-jmeter-{{ jmeter.version }}.tgz &&   mv -f /opt/apache-jmeter-{{ jmeter.version }}/ /opt/jmeter
  ignore_errors: yes

- name: Config  rm_keystore.jks
  copy: src=rmi_keystore.jks dest=/opt/jmeter/bin/rmi_keystore.jks  


- name: Install plugins
  unarchive:
    src: "{{ item }}"
    dest: "/opt/jmeter/"
    remote_src: yes
  with_items: "{{ jmeter.plugins }}"

- name: Set Java heap size
  lineinfile:
    path: "/opt/jmeter/bin/jmeter"
    regexp: '^HEAP='
    line: 'HEAP="-Xms{{ java.memory }} -Xmx{{ java.memory }}"'
 

- name: Config  run
  template: src=run.j2 dest=/opt/run-server.sh


- name: move folder jmeter
  shell: chmod +x /opt/run-server.sh
  ignore_errors: yes


- name: Config  supervisor
  copy: src=jmeter.conf dest=/etc/supervisor/conf.d/jmeter.conf

