---


- name: install mysql
  apt:
   name="{{ item }}"
   state=present 
   update_cache=true
  with_items:
   - python-mysqldb
   - mysql-server
   - libmysqlclient-dev 

- name: Install the Python MySQLB module
  pip: name=mysql-python

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
      - "{{ mysql_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost 