---
- name: Creating prometheus user group
  group: name="{{node_export_groupId}}"
  become: true

- name: Creating prometheus user
  user:
    name: "{{node_export_userId}}"
    group: "{{node_export_groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{node_export_userId}} nologin User"
    createhome: "no"
    state: present

- name: Install prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_export_version }}/node_exporter-{{ node_export_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus node exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ node_export_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{node_export_userId}}"
    group: "{{node_export_groupId}}"
    remote_src: yes
    mode: 0755

- name: Delete node exporter tmp folder
  file:
    path: '/tmp/node_exporter-{{ node_export_version }}.linux-amd64'
    state: absent

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: Check if node exporter emits metrices
  uri:
    url: http://127.0.0.1:9100/metrics
    method: GET
    status_code: 200