---

- name: update repository 
  shell: yum -y update
  ignore_errors: yes


  
- name: add repository 
  shell:  yum install -y yum-utils device-mapper-persistent-data lvm2
  ignore_errors: yes


- name: add repository 
  shell:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  ignore_errors: yes



- name: add repository 
  shell:  yum install -y  docker-ce docker-ce-cli containerd.io
  ignore_errors: yes




- name: Creates directory openshift
  file:
    path: /opt/openshift
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    dest: /opt/openshift
    remote_src: yes


- name: mv oc
  shell: cd /opt/openshift/openshift-origin-client*/ ; mv  oc kubectl  /usr/local/bin/
  ignore_errors: yes

- name: Config serv
  shell: 'echo { \"insecure-registries\" : [ \"172.30.0.0/16\" ] } > /etc/docker/daemon.json'
  ignore_errors: yes


- name: restart
  shell: systemctl daemon-reload;systemctl restart docker;systemctl enable docker;echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf ; sysctl -p
  ignore_errors: yes


#- name: mv oc
#  shell: oc cluster up 
#  ignore_errors: yes  

- name: create cluster
  shell: /usr/local/bin/oc cluster up  --public-hostname={{ openshift_ip_public }}
  ignore_errors: yes