---

- name: add repository 
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  ignore_errors: yes


  
- name: add repository 
  shell:  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  ignore_errors: yes


- name: install docker
  apt:
   name="{{ item }}"
   state=present 
  with_items:
   - curl
   - docker.io
   - wget 


- name: Creates directory openshift
  file:
    path: /opt/openshift
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    dest: /opt/openshift
    remote_src: yes


- name: mv oc
  shell: cd /opt/openshift/openshift-origin-client*/ ; mv  oc kubectl  /usr/local/bin/
  ignore_errors: yes

- name: Config service registry docker
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: restart docker
  systemd:
    name: docker
    state: restarted
  

- name: mv oc
  shell: oc cluster up --routing-suffix={{ openshift_ip_public }}.{{ openshift_domain_public }} --public-hostname={{ openshift_ip_public }}
  ignore_errors: yes