cluster.name: elasticsearch
node.name: node-1

path.data: /var/lib/elasticsearch

path.logs: /var/log/elasticsearch

http.host: {{ kibana.es_ip }}

network.host: 0.0.0.0
http.port: {{ kibana.es_port }}

discovery.seed_hosts: ["{{ kibana.es_ip }}"]
